all:
  hosts:
    master:
      ansible_host: 62.84.119.45
      access_ip: 62.84.119.45
      ip: 192.168.100.17
      ansible_user: ubuntu
    worker1:
      ansible_host: 84.201.139.30
      access_ip: 84.201.139.30
      ip: 192.168.110.24
      ansible_user: ubuntu
    worker2:
      ansible_host: 158.160.193.134
      access_ip: 158.160.193.134
      ip: 192.168.120.9
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: