all:
  hosts:
    master:
      ansible_host: 158.160.62.47
      access_ip: 158.160.62.47
      ip: 192.168.100.33
      ansible_user: ubuntu
    worker1:
      ansible_host: 89.169.183.135
      access_ip: 89.169.183.135
      ip: 192.168.110.17
      ansible_user: ubuntu
    worker2:
      ansible_host: 158.160.157.0
      access_ip: 158.160.157.0
      ip: 192.168.120.26
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: