all:
  hosts:
    master:
      ansible_host: 84.201.135.15
      access_ip: 84.201.135.15
      ip: 192.168.100.8
      ansible_user: ubuntu
    worker1:
      ansible_host: 89.169.191.150
      access_ip: 89.169.191.150
      ip: 192.168.110.33
      ansible_user: ubuntu
    worker2:
      ansible_host: 158.160.188.232
      access_ip: 158.160.188.232
      ip: 192.168.120.21
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: