all:
  hosts:
    master:
      ansible_host: 158.160.57.73
      access_ip: 158.160.57.73
      ip: 192.168.100.14
      ansible_user: ubuntu
    worker1:
      ansible_host: 84.201.164.7
      access_ip: 84.201.164.7
      ip: 192.168.110.33
      ansible_user: ubuntu
    worker2:
      ansible_host: 158.160.187.46
      access_ip: 158.160.187.46
      ip: 192.168.120.17
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: